### ISSUE TITLE
Quarkus CLI won't install

### ISSUE THREAD

**Issue by edeandrea** [jbangdev/jbang#928]
On macOS I'm trying to install the Quarkus CLI by following this guide: https://quarkus.io/version/main/guides/cli-tooling

When I run the install command `curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio` I get errors:

```shell
bash: line 100: [: missing ']'
bash: line 100: -f: command not found
```

The install continues and says that its installed correctly but it doesn't seem to work. After restarting my terminal (or even without restarting my terminal) I get `quarkus: command not found` when trying to run `quarkus --version`.

Additionally, I installed jbang via homebrew and then ran `jbang app install --fresh --force quarkus@quarkusio`. That didn't produce any errors but it also didn't install the quarkus cli. I still get `quarkus: command not found` when trying to run `quarkus --version`.

I'm on macOS 11.4

```shell
bash --version
GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin20.3.0)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
```

**Comment by maxandersen** [comment]
https://github.com/jbangdev/jbang/blame/a6b7fafeff42350dd82a44529b1f86104b1217a4/src/main/scripts/jbang#L100 was changed in https://github.com/jbangdev/jbang/pull/883

@quintesse I think changing to use [[ ]] instead of [ ] would fix it?

**Comment by maxandersen** [comment]
https://stackoverflow.com/questions/15257313/multiple-conditions-variables-in-bash-script explains whats happening here

**Comment by edeandrea** [comment]
After successfully installing

```shell
edeandre@edeandre-mac:~$ jbang app install --fresh --force quarkus@quarkusio
jbang app install --fresh --force quarkus@quarkusio
[jbang] Command installed: quarkus
edeandre@edeandre-mac:~$ quarkus --version
quarkus --version
Client Version 2.0.0.CR3
```

I closed my terminal & re-opened. Running `quarkus --version` I then get `quarkus: command not found`

**Comment by axblu** [comment]
@edeandrea I can't reproduce that with Ubuntu (in WSL).

**Comment by edeandrea** [comment]
![Screen Shot 2021-06-09 at 10 38 31 AM](https://user-images.githubusercontent.com/363447/121375602-da0de180-c90e-11eb-838b-b78c0ea1f0c9.png)

**Comment by axblu** [comment]
@edeandrea It works for me. Maybe this is specific to macOS?

**Comment by edeandrea** [comment]
No idea. All I know is it doesn't work for me.

**Comment by maxandersen** [comment]
this is fixed - @axblu my guess is you tried just after I fixed it :)

**Comment by edeandrea** [comment]
@maxandersen unless you did something today it is still broken for me.

**Comment by maxandersen** [comment]
@edeandrea what error are you seeing - the original one about `bash: line 100: [: missing ']'` or that `quarkus` app not found after `jbang app install` ?

**Comment by edeandrea** [comment]
See my comment above

https://github.com/jbangdev/jbang/issues/928#issuecomment-857741220

**Comment by quintesse** [comment]
@maxandersen I don't think `app install` is compatible with using `curl`. At least not without having run `app setup` at some point. (At which point using `curl` becomes somewhat unnecessary)

**Comment by maxandersen** [comment]
hmmmm - last time we discussed you said `jbang app install` would check setup no matter what - if that isn't the case then sure this would fail.

**Comment by maxandersen** [comment]
@edeandrea please try `curl -Ls https://sh.jbang.dev | bash -s - app setup` or simply `jbang app setup` - fit that fixes it we know why :)

**Comment by maxandersen** [comment]
...and you get this

**Comment by edeandrea** [comment]
```shell
edeandre@edeandre-mac:~$ grep jbang ~/.zshrc ~/.bashrc
/Users/edeandre/.zshrc:alias j!=jbang
/Users/edeandre/.zshrc:export PATH="$HOME/.jbang/bin:$PATH"
/Users/edeandre/.bashrc:alias j!=jbang
/Users/edeandre/.bashrc:export PATH="$HOME/.jbang/bin:$PATH"
edeandre@edeandre-mac:~$ echo $PATH
/Users/edeandre/.sdkman/candidates/java/current/bin:/Users/edeandre/tools/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/munki
edeandre@edeandre-mac:~$ jbang app setup
[jbang] Jbang environment is already set up.
edeandre@edeandre-mac:~$ quarkus --version
-bash: quarkus: command not found

```

**Comment by quintesse** [comment]
@maxandersen I think you've got it backwards :-)
It's running `jbang app setup` that will make sure that `jbang app install jbang` is also being done, not the other way around.
(That why the documentation tells people to run `curl -Ls https://sh.jbang.dev | bash -s - app setup`)

**Comment by maxandersen** [comment]
so...what else in your setup mutates PATH as its set in your rc files but the PATH does not contain it?

**Comment by edeandrea** [comment]
this is what I have in my `~/.bash_profile`

```shell
export GRAALVM_HOME=~/.sdkman/candidates/java/21.1.0.r16-grl
export TOOLS_BIN=~/tools/bin
export PATH=$TOOLS_BIN:$PATH

alias syncfork='gitsync master'
alias syncmainfork="gitsync main"
alias syncforkreturn='syncfork && git checkout @{-1}'
alias synctags='git tag -l | xargs git tag -d && git fetch -t'
alias syncupstreamtags='git tag -l | xargs git tag -d && git fetch -t upstream'
alias kerb='kinit -t ~/.kerberos.username.keytab -k edeandre@REDHAT.COM'
alias sshpeople="ssh `whoami`@people.redhat.com"
alias oc4="~/tools/oc4/oc"
alias mvn35="~/tools/apache-maven-3.5.4/bin/mvn"

# Color schemes
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\W\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
#export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

alias ls='ls -GFh'

# For bash completion
if [ -f /usr/local/etc/profile.d/bash_completion.sh ]; then
  [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
fi

if [ -f $(brew --prefix)/etc/bash_completion ]; then
  . $(brew --prefix)/etc/bash_completion
fi

# For git syncing
function gitsync() {
  git fetch upstream && git checkout $1 && git merge upstream/$1 && git push
}

function rss() {
  ps -o pid,rss,command -p $(pgrep -f $1)
}

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/edeandre/.sdkman"
[[ -s "/Users/edeandre/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/edeandre/.sdkman/bin/sdkman-init.sh"
```

**Comment by edeandrea** [comment]
> Did you try with a new shell @edeandrea ?

I opened a new shell and did `curl -Ls https://sh.jbang.dev | bash -s - app setup`. Then in a new shell I did `jbang app install --fresh --force quarkus@quarkusio`. Then in a new shell `quarkus --version` returns `quarkus: command not found`

**Comment by maxandersen** [comment]
is your .bashrc even executed ? try add a "echo JBANG WAS HERE!" next to the path modification.

**Comment by edeandrea** [comment]
I added `echo "JBANG WAS HERE!"` to `~/.bashrc` and when I opened a new shell I did not see the message

**Comment by edeandrea** [comment]
macOS doesn't use `.bashrc` I don't think. It uses`.bash_profile`

**Comment by edeandrea** [comment]
https://stackoverflow.com/questions/7780030/how-to-fix-terminal-not-loading-bashrc-on-os-x-lion

**Comment by edeandrea** [comment]
https://scriptingosx.com/2017/04/about-bash_profile-and-bashrc-on-macos/

   > However, Terminal.app on macOS, does not follow this convention. When Terminal.app opens a new window, it will run .bash_profile. Not, as users familiar with other Unix systems would expect, .bashrc.

**Comment by edeandrea** [comment]
I added `[[ -s ~/.bashrc ]] && source ~/.bashrc` to the top of my `~/.bash_profile` and after restarting my terminal all is good :)

**Comment by edeandrea** [comment]
@maxandersen Maybe you and I can have a conversation where you try to convince me not to use the Terminal app anymore :)

**Comment by maxandersen** [comment]
We need to handle this properly somehow.

**Comment by maxandersen** [comment]
opening https://github.com/jbangdev/jbang/issues/930 for the osx bash/terminal issue. this one about [] is fixed.
